blank_issues_enabled: false
contact_links:
  - name: Support question â“
    url: https://github.com/kingdutch/cucumber-linter/discussions/new
    about: Please open a new discussion instead. Thank you.
